version: '3.7'

services:
  fm-server:
    container_name: fm-server
    networks:
      - fm-net
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_NAME}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      REDIS_HOST: fm-redis
      SENDGRID: ${SENDGRID}
    volumes:
      - ./server/src:/app/src
    ports:
      - 5050:8080
    depends_on:
      - fm-redis

  fm-sellers:
    container_name: fm-sellers
    networks:
      - fm-net
    build:
      context: ./sellers
      dockerfile: dev.Dockerfile
    ports:
      - 3030:80
    volumes:
      - ./sellers/assets:/app/assets
      - ./sellers/components:/app/components
      - ./sellers/fonts:/app/fonts
      - ./sellers/graphql:/app/graphql
      - ./sellers/lib:/app/lib
      - ./sellers/pages:/app/pages
      - ./sellers/public:/app/public
      - ./sellers/utils:/app/utils

  fm-buyers:
    container_name: fm-buyers
    networks:
      - fm-net
    build:
      context: ./buyers
      dockerfile: dev.Dockerfile
    ports:
      - 2020:80
    volumes:
      - ./buyers/assets:/app/assets
      - ./buyers/components:/app/components
      - ./buyers/fonts:/app/fonts
      - ./buyers/graphql:/app/graphql
      - ./buyers/lib:/app/lib
      - ./buyers/pages:/app/pages
      - ./buyers/public:/app/public
      - ./buyers/utils:/app/utils

  fm-redis:
    container_name: fm-redis
    networks:
      - fm-net
    image: redis:latest

  fm-db:
    container_name: fm-db
    networks:
      - fm-net
    build:
      context: ./database
      dockerfile: dev.Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - 15432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    container_name: fm-nginx
    build:
      context: ./nginx
      dockerfile: dev.Dockerfile
    networks:
      - fm-net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - fm-db
      - fm-server
    logging:
      driver: none

volumes:
  pgdata:

networks:
  fm-net:
