-- INSERT INTO "fm"."menus" ("tenant_id", "title") VALUES ('5', 'Chicken Deals');
-- INSERT INTO "fm"."menus" ("tenant_id", "title") VALUES ('5', 'All Pizzas');
-- INSERT INTO "fm"."menus" ("tenant_id", "title") VALUES ('5', 'Chefs Finest');
-- INSERT INTO "fm"."menus" ("tenant_id", "title") VALUES ('5', 'Desert Delight!');
-- INSERT INTO "fm"."menus" ("tenant_id", "title") VALUES ('5', 'Vietnamese Meals');
-- INSERT INTO "fm"."menus" ("tenant_id", "title") VALUES ('5', 'Dollar Menu');
-- INSERT INTO "fm"."menus" ("tenant_id", "title") VALUES ('5', 'Side Menu');
