-- INSERT INTO "fm"."menuchoices" ("organization_id", "header", "sub_header") VALUES ('5', 'Add Toppings', 'Choose as many as you would like');
-- INSERT INTO "fm"."menuchoices" ("organization_id", "header", "sub_header") VALUES ('5', 'Choose Cheese', 'Choose as many as you would like');
-- INSERT INTO "fm"."menuchoices" ("organization_id", "header", "sub_header") VALUES ('5', 'Choose Dip', 'Choose One');
-- INSERT INTO "fm"."menuchoices" ("organization_id", "header", "sub_header") VALUES ('5', 'Choose Crust', 'Choose One');
-- INSERT INTO "fm"."menuchoices" ("organization_id", "header", "sub_header") VALUES ('5', 'Choose up to two', 'Choose between 1 and 2');
-- INSERT INTO "fm"."menuchoices" ("organization_id", "header", "sub_header") VALUES ('5', 'Add Extra Toppings', 'Choose as many as you would like');
-- INSERT INTO "fm"."menuchoices" ("organization_id", "header", "sub_header") VALUES ('5', 'Choose Dips', 'Choose Exactly 2');